sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_install:
  - rvm use @global
  - gem uninstall bundler -x
  - gem install bundler --version=1.13.7
  - bundler --version
install:
  - bundle install --without development
  - 'cd publify_core && bundle install'
  - 'cd ../publify_amazon_sidebar && bundle install'
  - 'cd ../publify_textfilter_code && bundle install'
before_script:
  - bundle exec rake db:create db:migrate
script: 'bundle exec rake\
  && cd publify_core && bundle exec rake\
  && cd ../publify_amazon_sidebar && bundle exec rake\
  && cd ../publify_textfilter_code && bundle exec rake'

#after_success:
#  - bundle exec codeclimate-test-reporter

branches:
  only:
    - master

addons:
  code_climate:
    repo_token: 8850bccc6911d74965627b1fafe753beb368fab00d33de0c7576c6598fc1220e

notifications:
  webhooks:
    urls:
      - http://publify_hook.ookook.fr/travisci
    on_success: always
    on_failure: never
    on_start: never
